### ISSUE TITLE
appengine-maven-plugin vs app-maven-plugin

### ISSUE THREAD

**Issue by hshang09** [GoogleCloudPlatform/appengine-maven-plugin#90]
What's the difference between app-maven-plugin and appengine-maven-plugin (https://github.com/GoogleCloudPlatform/app-maven-plugin)? 

When to use which?

**Comment by chanseokoh** [comment]
Please see https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/260#issuecomment-374638498.

**Comment by hshang09** [comment]
I see. Thank you @chanseokoh.
